services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/${REPO_NAME}:latest
    container_name: entrytrackr_app
    ports:
      - "5000:5000"
    networks:
      - app_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000"]
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  app_network:
    driver: bridge