services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/${REPO_NAME}:latest
    container_name: entrytrackr_app
    ports:
      - "5000:5000"
    networks:
      - app_network
      - db_network
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: ${MYSQL_PORT}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5000" ]
      interval: 15s
      timeout: 3s
      retries: 3  
    depends_on:
      - mysql
    
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  db_data:
    driver: local