services:
  app:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    container_name: EntryTrackr_app
    ports:
      - "5000:5000"
    networks:
      - app_network
      - db_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:5000" ]
      interval: 15s
      timeout: 3s
      retries: 3  
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - db_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge
volumes:
  db_data:
    driver: local